"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PmcBotTypes = exports.ConversionBotTypes = exports.BotDifficultyTypes = exports.BotBrainTypes = exports.AllBotTypes = void 0;
var AllBotTypes;
(function (AllBotTypes) {
    AllBotTypes["BEAR"] = "sptBear";
    AllBotTypes["BIGPIPE"] = "followerBigPipe";
    AllBotTypes["BIRDEYE"] = "followerBirdEye";
    AllBotTypes["BLOODHOUND"] = "arenaFighterEvent";
    AllBotTypes["BLOODHOUND_UNUSED"] = "arenaFighter";
    AllBotTypes["CULTIST_PRIEST"] = "sectantPriest";
    AllBotTypes["CULTIST_WARRIOR"] = "sectantWarrior";
    AllBotTypes["CURSED_SCAV"] = "cursedAssault";
    AllBotTypes["GLUKHAR"] = "bossGluhar";
    AllBotTypes["GLUKHAR_ASSAULT_FOLLOWER"] = "followerGluharAssault";
    AllBotTypes["GLUKHAR_SCOUT_FOLLOWER"] = "followerGluharScout";
    AllBotTypes["GLUKHAR_SECURITY_FOLLOWER"] = "followerGluharSecurity";
    AllBotTypes["GLUKHAR_SNIPER_FOLLOWER"] = "followerGluharSnipe";
    AllBotTypes["KABAN"] = "bossBoar";
    AllBotTypes["KABAN_GUARD_FOLLOWER"] = "followerBoar";
    AllBotTypes["KABAN_GUARD_FOLLOWER_CLOSE_ONE"] = "followerBoarClose1";
    AllBotTypes["KABAN_GUARD_FOLLOWER_CLOSE_TWO"] = "followerBoarClose2";
    AllBotTypes["KABAN_SNIPER_FOLLOWER"] = "bossBoarSniper";
    AllBotTypes["KILLA"] = "bossKilla";
    AllBotTypes["KNIGHT"] = "bossKnight";
    AllBotTypes["KOLLONTAY"] = "bossKolontay";
    AllBotTypes["KOLLONTAY_ASSAULT_FOLLOWER"] = "followerKolontayAssault";
    AllBotTypes["KOLLONTAY_SECURITY_FOLLOWER"] = "followerKolontaySecurity";
    AllBotTypes["RAIDER"] = "pmcBot";
    AllBotTypes["RESHALA"] = "bossBully";
    AllBotTypes["RESHALA_FOLLOWER"] = "followerBully";
    AllBotTypes["ROGUE"] = "exUsec";
    AllBotTypes["SANITAR"] = "bossSanitar";
    AllBotTypes["SANITAR_FOLLOWER"] = "followerSanitar";
    AllBotTypes["SCAV"] = "assault";
    AllBotTypes["SHTURMAN"] = "bossKojaniy";
    AllBotTypes["SHTURMAN_FOLLOWER"] = "followerKojaniy";
    AllBotTypes["SNIPERSCAV"] = "marksman";
    AllBotTypes["TAGILLA"] = "bossTagilla";
    AllBotTypes["TAGILLA_FOLLOWER"] = "followerTagilla";
    AllBotTypes["USEC"] = "sptUsec";
    AllBotTypes["WEIRD_SCAV"] = "crazyAssaultEvent";
    AllBotTypes["ZRYACHIY"] = "bossZryachiy";
    AllBotTypes["ZRYACHIY_FOLLOWER"] = "followerZryachiy";
})(AllBotTypes || (exports.AllBotTypes = AllBotTypes = {}));
var BotBrainTypes;
(function (BotBrainTypes) {
    BotBrainTypes["BIGPIPE"] = "followerBigPipe";
    BotBrainTypes["BLOODHOUND"] = "arenaFighterEvent";
    BotBrainTypes["BLOODHOUND_UNUSED"] = "arenaFighter";
    BotBrainTypes["CURSED_SCAV"] = "cursedAssault";
    BotBrainTypes["GLUKHAR"] = "bossGluhar";
    BotBrainTypes["GLUKHAR_ASSAULT_FOLLOWER"] = "followerGluharAssault";
    BotBrainTypes["KABAN"] = "bossBoar";
    BotBrainTypes["KILLA"] = "bossKilla";
    BotBrainTypes["KNIGHT"] = "bossKnight";
    BotBrainTypes["RAIDER"] = "pmcBot";
    BotBrainTypes["RESHALA_FOLLOWER"] = "followerBully";
    BotBrainTypes["ROGUE"] = "exUsec";
    BotBrainTypes["SANITAR"] = "bossSanitar";
    BotBrainTypes["SANITAR_FOLLOWER"] = "followerSanitar";
    BotBrainTypes["SCAV"] = "assault";
    BotBrainTypes["TAGILLA"] = "bossTagilla";
    BotBrainTypes["WEIRD_SCAV"] = "crazyAssaultEvent";
    BotBrainTypes["ZRYACHIY"] = "bossZryachiy";
})(BotBrainTypes || (exports.BotBrainTypes = BotBrainTypes = {}));
var BotDifficultyTypes;
(function (BotDifficultyTypes) {
    BotDifficultyTypes["EASY"] = "easy";
    BotDifficultyTypes["NORMAL"] = "normal";
    BotDifficultyTypes["HARD"] = "hard";
    BotDifficultyTypes["IMPOSSIBLE"] = "impossible";
})(BotDifficultyTypes || (exports.BotDifficultyTypes = BotDifficultyTypes = {}));
var ConversionBotTypes;
(function (ConversionBotTypes) {
    ConversionBotTypes["BLOODHOUND"] = "arenafighterevent";
    ConversionBotTypes["BLOODHOUND_UNUSED"] = "arenafighter";
    ConversionBotTypes["CURSED_SCAV"] = "cursedassault";
    ConversionBotTypes["RAIDER"] = "pmcbot";
    ConversionBotTypes["ROGUE"] = "exusec";
    ConversionBotTypes["SCAV"] = "assault";
    ConversionBotTypes["WEIRD_SCAV"] = "crazyassaultevent";
})(ConversionBotTypes || (exports.ConversionBotTypes = ConversionBotTypes = {}));
var PmcBotTypes;
(function (PmcBotTypes) {
    PmcBotTypes["BEAR"] = "bear";
    PmcBotTypes["USEC"] = "usec";
})(PmcBotTypes || (exports.PmcBotTypes = PmcBotTypes = {}));
