"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LocationNames = exports.AltLocationNames = void 0;
var AltLocationNames;
(function (AltLocationNames) {
    AltLocationNames["CUSTOMS"] = "bigmap";
    AltLocationNames["FACTORY_DAY"] = "factory4_day";
    AltLocationNames["FACTORY_NIGHT"] = "factory4_night";
    AltLocationNames["GROUNDZERO"] = "sandbox";
    AltLocationNames["INTERCHANGE"] = "interchange";
    AltLocationNames["LABORATORY"] = "laboratory";
    AltLocationNames["LIGHTHOUSE"] = "lighthouse";
    AltLocationNames["RESERVE"] = "rezervbase";
    AltLocationNames["SHORELINE"] = "shoreline";
    AltLocationNames["STREETS"] = "tarkovstreets";
    AltLocationNames["WOODS"] = "woods";
})(AltLocationNames || (exports.AltLocationNames = AltLocationNames = {}));
var LocationNames;
(function (LocationNames) {
    LocationNames["CUSTOMS"] = "customs";
    LocationNames["FACTORY"] = "factory";
    LocationNames["GROUNDZERO"] = "groundzero";
    LocationNames["INTERCHANGE"] = "interchange";
    LocationNames["LABORATORY"] = "labs";
    LocationNames["LIGHTHOUSE"] = "lighthouse";
    LocationNames["RESERVE"] = "reserve";
    LocationNames["SHORELINE"] = "shoreline";
    LocationNames["STREETS"] = "streets";
    LocationNames["WOODS"] = "woods";
})(LocationNames || (exports.LocationNames = LocationNames = {}));
